name: Daily GS/WETH Straddle Alert

on:
  schedule:
    - cron: '5 0 * * *'      # runs every day at 00:05 UTC
  workflow_dispatch:        # manual “Run workflow” button

jobs:
  run-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run straddle alert
        env:
          PUSHCUT_WEBHOOK_URL: ${{ secrets.PUSHCUT_WEBHOOK_URL }}
        run: python pushcut_alert.py
SUBGRAPH = "https://api.thegraph.com/subgraphs/name/ianlapham/arbitrum-minimal"
PAIR     = "0x223292964fd10e82867d9e6c99ce62106426f204"
df = pd.DataFrame(data).assign(
    timestamp=lambda d: pd.to_datetime(d.date, unit="s")
).set_index("timestamp")
